### ISSUE TITLE
'banana_tags' is not a registered tag library

### ISSUE THREAD

**Issue by ezesundayeze** [brack3t/Banana-Py#2]
This is the response I get after following the installation and configuration guidelines.

"TemplateSyntaxError at /abtest
'banana_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
humanize
i18n
l10n
log
rest_framework
static
staticfiles
tz"

I have have tried tio fixed this but I couldn't dind exactly where the oriblem is coming from. I have the app installed in the settings file.

**Comment by chrisjones-brack3t** [comment]
The last commit to this repo was over 7 years ago. I’m sure MailChimp’s API’s have changed or have been retired. You’d be better served using something like [python-mailchimp](https://github.com/charlesthk/python-mailchimp) that is in active development.

I’m going to close this issue and likely shut this repo down or add docs advising people to not use this.

**Comment by ezesundayeze** [comment]
Alright. 
Thanks.
